version: '3.1'

services:

  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    volumes:
      - ./sql/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: money-transfer-app
    ports:
      - '8080:8080'
      - '5005:5005'
    network_mode: "host"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: localhost
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 86400000  # TTL for one day in milliseconds

