CREATE TABLE ACCOUNTS (
    ID UUID PRIMARY KEY,
    OWNER_NAME VARCHAR(20),
    BALANCE DECIMAL(19, 4),
    CURRENCY VARCHAR(255),
    CREATED_AT TIMESTAMP,
    VERSION INT
);

CREATE TABLE TRANSACTIONS (
    ID UUID PRIMARY KEY,
    SOURCE_ACCOUNT_ID UUID,
    TARGET_ACCOUNT_ID UUID,
    AMOUNT DECIMAL(19, 4),
    CURRENCY VARCHAR(255),
    TRANSACTION_STATUS VARCHAR(255),
    MESSAGE VARCHAR(255),
    HASHED_PAYLOAD INT,
    HTTP_STATUS VARCHAR(10)
);

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_source_account
FOREIGN KEY (SOURCE_ACCOUNT_ID)
REFERENCES ACCOUNTS(ID);

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_target_account
FOREIGN KEY (TARGET_ACCOUNT_ID)
REFERENCES ACCOUNTS(ID);

